INSERT INTO public.themes_suggestions (id, first_letter, suggestion, theme)
VALUES
  (default, 'a', 'audi', 'carro'),
  (default, 'b', 'bmw', 'carro'),
  (default, 'c', 'chevrolet', 'carro'),
  (default, 'd', 'dodge', 'carro'),
  (default, 'e', 'ford', 'carro'),
  (default, 'f', 'fiat', 'carro'),
  (default, 'g', 'gmc', 'carro'),
  (default, 'h', 'honda', 'carro'),
  (default, 'i', 'infiniti', 'carro'),
  (default, 'j', 'jaguar', 'carro'),
  (default, 'k', 'kia', 'carro'),
  (default, 'l', 'lexus', 'carro'),
  (default, 'm', 'mercedes', 'carro'),
  (default, 'n', 'nissan', 'carro'),
  (default, 'o', 'opel', 'carro'),
  (default, 'p', 'peugeot', 'carro'),
  (default, 'q', 'quattro', 'carro'),
  (default, 'r', 'renault', 'carro'),
  (default, 's', 'subaru', 'carro'),
  (default, 't', 'toyota', 'carro'),
  (default, 'u', 'volkswagen', 'carro'),
  (default, 'v', 'volvo', 'carro'),
  (default, 'w', 'wuling', 'carro'),
  (default, 'x', 'xiaoke', 'carro'),
  (default, 'y', 'yugo', 'carro'),
  (default, 'z', 'zastava', 'carro');

INSERT INTO public.themes_suggestions (id, first_letter, suggestion, theme)
VALUES
  (default, 'a', 'acura', 'carro'),
  (default, 'b', 'bugatti', 'carro'),
  (default, 'c', 'cadillac', 'carro'),
  (default, 'd', 'daihatsu', 'carro'),
  (default, 'e', 'electra', 'carro'),
  (default, 'f', 'ferrari', 'carro'),
  (default, 'g', 'gaz', 'carro'),
  (default, 'h', 'hummer', 'carro'),
  (default, 'i', 'infiniti', 'carro'),
  (default, 'j', 'jaguar', 'carro'),
  (default, 'k', 'koenigsegg', 'carro'),
  (default, 'l', 'lamborghini', 'carro'),
  (default, 'm', 'maserati', 'carro'),
  (default, 'n', 'nissan', 'carro'),
  (default, 'o', 'opel', 'carro'),
  (default, 'p', 'porsche', 'carro'),
  (default, 'q', 'quattro', 'carro'),
  (default, 'r', 'rolls-royce', 'carro'),
  (default, 's', 'subaru', 'carro'),
  (default, 't', 'tesla', 'carro'),
  (default, 'u', 'ultima', 'carro'),
  (default, 'v', 'volkswagen', 'carro'),
  (default, 'w', 'wiesmann', 'carro'),
  (default, 'x', 'xiaoke', 'carro'),
  (default, 'y', 'yugo', 'carro'),
  (default, 'z', 'zenvo', 'carro');

INSERT INTO public.themes_suggestions (id, first_letter, suggestion, theme)
VALUES

  (default, 'a', 'Audi', 'carro'),
  (default, 'b', 'BMW', 'carro'),
  (default, 'c', 'Chevrolet', 'carro'),
  (default, 'd', 'Dodge', 'carro'),
  (default, 'e', 'Ford', 'carro'),
  (default, 'f', 'Ferrari', 'carro'),
  (default, 'g', 'GMC', 'carro'),
  (default, 'h', 'Honda', 'carro'),
  (default, 'i', 'Infiniti', 'carro'),
  (default, 'j', 'Jaguar', 'carro'),
  (default, 'k', 'Kia', 'carro'),
  (default, 'l', 'Lexus', 'carro'),
  (default, 'm', 'Mercedes', 'carro'),
  (default, 'n', 'Nissan', 'carro'),
  (default, 'o', 'Opel', 'carro'),
  (default, 'p', 'Porsche', 'carro'),
  (default, 'q', 'Quattro', 'carro'),
  (default, 'r', 'Renault', 'carro'),
  (default, 's', 'Subaru', 'carro'),
  (default, 't', 'Toyota', 'carro'),
  (default, 'u', 'Volkswagen', 'carro'),
  (default, 'v', 'Volvo', 'carro'),
  (default, 'w', 'Wuling', 'carro'),
  (default, 'x', 'Xiaoke', 'carro'),
  (default, 'y', 'Yugo', 'carro'),
  (default, 'z', 'Zastava', 'carro');

INSERT INTO public.themes_suggestions (id, first_letter, suggestion, theme)
VALUES
  (default, 'a', 'Apocalypse Now', 'filme'),
  (default, 'b', 'Blade Runner', 'filme'),
  (default, 'c', 'Citizen Kane', 'filme'),
  (default, 'd', 'The Dark Knight', 'filme'),
  (default, 'e', 'Eternal Sunshine of the Spotless Mind', 'filme'),
  (default, 'f', 'Fight Club', 'filme'),
  (default, 'g', 'Goodfellas', 'filme'),
  (default, 'h', 'The Hurt Locker', 'filme'),
  (default, 'i', 'Inglourious Basterds', 'filme'),
  (default, 'j', 'Jaws', 'filme'),
  (default, 'k', 'Kill Bill', 'filme'),
  (default, 'l', 'The Lord of the Rings: The Two Towers', 'filme'),
  (default, 'm', 'The Shawshank Redemption', 'filme'),
  (default, 'n', 'No Country for Old Men', 'filme'),
  (default, 'o', 'One Flew Over the Cuckoos Nest', 'filme'),
  (default, 'p', 'The Pianist', 'filme'),
  (default, 'q', 'A Quiet Place', 'filme'),
  (default, 'r', 'Reservoir Dogs', 'filme'),
  (default, 's', 'The Silence of the Lambs', 'filme'),
  (default, 't', 'The Terminator', 'filme'),
  (default, 'u', 'Up', 'filme'),
  (default, 'v', 'V for Vendetta', 'filme'),
  (default, 'w', 'The Witch', 'filme'),
  (default, 'x', 'X-Men: First Class', 'filme'),
  (default, 'y', 'Y Tu Mamá Tambien', 'filme'),
  (default, 'z', 'Zodiac', 'filme');


INSERT INTO public.themes_suggestions (id, first_letter, suggestion, theme)
VALUES
  (default, 'a', 'American Beauty', 'filme'),
  (default, 'b', 'Black Swan', 'filme'),
  (default, 'c', 'The Conjuring', 'filme'),
  (default, 'd', 'Donnie Darko', 'filme'),
  (default, 'e', 'Eyes Wide Shut', 'filme'),
  (default, 'f', 'The French Connection', 'filme'),
  (default, 'g', 'The Grand Budapest Hotel', 'filme'),
  (default, 'h', 'The Hateful Eight', 'filme'),
  (default, 'i', 'Inside Out', 'filme'),
  (default, 'j', 'Jurassic World', 'filme'),
  (default, 'k', 'The Kings Speech', 'filme'),
  (default, 'l', 'La La Land', 'filme'),
  (default, 'm', 'The Martian', 'filme'),
  (default, 'n', 'Noah', 'filme'),
  (default, 'o', 'Oceans Eleven', 'filme'),
  (default, 'p', 'Pirates of the Caribbean', 'filme'),
  (default, 'q', 'Quantum of Solace', 'filme'),
  (default, 'r', 'Ratatouille', 'filme'),
  (default, 's', 'Se7en', 'filme'),
  (default, 't', 'Trainspotting', 'filme'),
  (default, 'u', 'Up in the Air', 'filme'),
  (default, 'v', 'Valkyrie', 'filme'),
  (default, 'w', 'The Wolf of Wall Street', 'filme'),
  (default, 'x', 'X-Men: Days of Future Past', 'filme'),
  (default, 'y', 'Y tu mamá tambien', 'filme'),
  (default, 'z', 'Zero Dark Thirty', 'filme');

INSERT INTO public.themes_suggestions (id, first_letter, suggestion, theme)
VALUES
  (default, 'a', 'Amelie', 'filme'),
  (default, 'b', 'Birdman', 'filme'),
  (default, 'c', 'Casino Royale', 'filme'),
  (default, 'd', 'Django Unchained', 'filme'),
  (default, 'e', 'Ex Machina', 'filme'),
  (default, 'f', 'Fargo', 'filme'),
  (default, 'g', 'Gone Girl', 'filme'),
  (default, 'h', 'Her', 'filme'),
  (default, 'i', 'Inception', 'filme'),
  (default, 'j', 'Juno', 'filme'),
  (default, 'k', 'Kill Bill: Vol. 2', 'filme'),
  (default, 'l', 'Lost in Translation', 'filme'),
  (default, 'm', 'Moonlight', 'filme'),
  (default, 'n', 'No Country for Old Men', 'filme'),
  (default, 'o', 'Oldboy', 'filme'),
  (default, 'p', 'Pans Labyrinth', 'filme'),
  (default, 'q', 'A Quiet Place', 'filme'),
  (default, 'r', 'Requiem for a Dream', 'filme'),
  (default, 's', 'The Social Network', 'filme'),
  (default, 't', 'The Truman Show', 'filme'),
  (default, 'u', 'Unbreakable', 'filme'),
  (default, 'v', 'V for Vendetta', 'filme'),
  (default, 'w', 'Whiplash', 'filme'),
  (default, 'x', 'X-Men: First Class', 'filme'),
  (default, 'y', 'Y Tu Mamá Tambien', 'filme'),
  (default, 'z', 'Zodiac', 'filme');


INSERT INTO public.themes_suggestions (id, first_letter, suggestion, theme)
VALUES
  (default, 'a', 'Argentina', 'pais'),
  (default, 'b', 'Brasil', 'pais'),
  (default, 'c', 'Canadá', 'pais'),
  (default, 'd', 'Dinamarca', 'pais'),
  (default, 'e', 'Egito', 'pais'),
  (default, 'f', 'França', 'pais'),
  (default, 'g', 'Grecia', 'pais'),
  (default, 'h', 'Holanda', 'pais'),
  (default, 'i', 'Itália', 'pais'),
  (default, 'j', 'Japao', 'pais'),
  (default, 'k', 'Kuwait', 'pais'),
  (default, 'l', 'Luxemburgo', 'pais'),
  (default, 'm', 'Mexico', 'pais'),
  (default, 'n', 'Noruega', 'pais'),
  (default, 'o', 'Oma', 'pais'),
  (default, 'p', 'Portugal', 'pais'),
  (default, 'q', 'Quênia', 'pais'),
  (default, 'r', 'Rússia', 'pais'),
  (default, 's', 'Suiça', 'pais'),
  (default, 't', 'Tailândia', 'pais'),
  (default, 'u', 'Ucrânia', 'pais'),
  (default, 'v', 'Venezuela', 'pais'),
  (default, 'w', 'Wales', 'pais'),
  (default, 'x', 'Xingu', 'pais'),
  (default, 'y', 'Yemen', 'pais'),
  (default, 'z', 'Zimbábue', 'pais');

INSERT INTO public.themes_suggestions (id, first_letter, suggestion, theme)
VALUES
  (default, 'a', 'Austrália', 'pais'),
  (default, 'b', 'Belgica', 'pais'),
  (default, 'c', 'Chile', 'pais'),
  (default, 'd', 'Djibouti', 'pais'),
  (default, 'e', 'Espanha', 'pais'),
  (default, 'f', 'Finlândia', 'pais'),
  (default, 'g', 'Gana', 'pais'),
  (default, 'h', 'Hungria', 'pais'),
  (default, 'i', 'Irlanda', 'pais'),
  (default, 'j', 'Jamaica', 'pais'),
  (default, 'k', 'Quênia', 'pais'),
  (default, 'l', 'Libano', 'pais'),
  (default, 'm', 'Malta', 'pais'),
  (default, 'n', 'Nepal', 'pais'),
  (default, 'o', 'Oma', 'pais'),
  (default, 'p', 'Polônia', 'pais'),
  (default, 'q', 'Qatar', 'pais'),
  (default, 'r', 'Romênia', 'pais'),
  (default, 's', 'Singapura', 'pais'),
  (default, 't', 'Turquia', 'pais'),
  (default, 'u', 'Uganda', 'pais'),
  (default, 'v', 'Vietna', 'pais'),
  (default, 'w', 'Wallis e Futuna', 'pais'),
  (default, 'x', 'Xingu', 'pais'),
  (default, 'y', 'Yemen', 'pais'),
  (default, 'z', 'Zâmbia', 'pais');

INSERT INTO public.themes_suggestions (id, first_letter, suggestion, theme)
VALUES
  (default, 'a', 'Áustria', 'pais'),
  (default, 'b', 'Bolivia', 'pais'),
  (default, 'c', 'Croácia', 'pais'),
  (default, 'd', 'Djibouti', 'pais'),
  (default, 'e', 'Equador', 'pais'),
  (default, 'f', 'Filipinas', 'pais'),
  (default, 'g', 'Gana', 'pais'),
  (default, 'h', 'Hungria', 'pais'),
  (default, 'i', 'Indonesia', 'pais'),
  (default, 'j', 'Japao', 'pais'),
  (default, 'k', 'Quênia', 'pais'),
  (default, 'l', 'Libano', 'pais'),
  (default, 'm', 'Malta', 'pais'),
  (default, 'n', 'Nepal', 'pais'),
  (default, 'o', 'Oma', 'pais'),
  (default, 'p', 'Polônia', 'pais'),
  (default, 'q', 'Qatar', 'pais'),
  (default, 'r', 'Romênia', 'pais'),
  (default, 's', 'Servia', 'pais'),
  (default, 't', 'Turquia', 'pais'),
  (default, 'u', 'Ucrânia', 'pais'),
  (default, 'v', 'Venezuela', 'pais'),
  (default, 'w', 'Wallis e Futuna', 'pais'),
  (default, 'x', 'Xingu', 'pais'),
  (default, 'y', 'Yemen', 'pais'),
  (default, 'z', 'Zâmbia', 'pais');

INSERT INTO public.themes_suggestions (id, first_letter, suggestion, theme)
VALUES
  (default, 'a', 'Aspirina', 'nome de remedio'),
  (default, 'b', 'Benadryl', 'nome de remedio'),
  (default, 'c', 'Claritin', 'nome de remedio'),
  (default, 'd', 'Diazepam', 'nome de remedio'),
  (default, 'e', 'Esomeprazole', 'nome de remedio'),
  (default, 'f', 'Fluoxetine', 'nome de remedio'),
  (default, 'g', 'Gabapentin', 'nome de remedio'),
  (default, 'h', 'Hydrochlorothiazide', 'nome de remedio'),
  (default, 'i', 'Ibuprofen', 'nome de remedio'),
  (default, 'j', 'Januvia', 'nome de remedio'),
  (default, 'k', 'Ketorolac', 'nome de remedio'),
  (default, 'l', 'Lisinopril', 'nome de remedio'),
  (default, 'm', 'Metformin', 'nome de remedio'),
  (default, 'n', 'Naproxen', 'nome de remedio'),
  (default, 'o', 'Omeprazole', 'nome de remedio'),
  (default, 'p', 'Prozac', 'nome de remedio'),
  (default, 'q', 'Quetiapine', 'nome de remedio'),
  (default, 'r', 'Risperidone', 'nome de remedio'),
  (default, 's', 'Sertraline', 'nome de remedio'),
  (default, 't', 'Tamsulosin', 'nome de remedio'),
  (default, 'u', 'Uloric', 'nome de remedio'),
  (default, 'v', 'Viagra', 'nome de remedio'),
  (default, 'w', 'Wellbutrin', 'nome de remedio'),
  (default, 'x', 'Xanax', 'nome de remedio'),
  (default, 'y', 'Yaz', 'nome de remedio'),
  (default, 'z', 'Zoloft', 'nome de remedio');

INSERT INTO public.themes_suggestions (id, first_letter, suggestion, theme)
VALUES
  (default, 'a', 'Advil', 'nome de remedio'),
  (default, 'b', 'Buspar', 'nome de remedio'),
  (default, 'c', 'Celebrex', 'nome de remedio'),
  (default, 'd', 'Dexedrine', 'nome de remedio'),
  (default, 'e', 'Eskalith', 'nome de remedio'),
  (default, 'f', 'Focalin', 'nome de remedio'),
  (default, 'g', 'Gleevec', 'nome de remedio'),
  (default, 'h', 'Hyzaar', 'nome de remedio'),
  (default, 'i', 'Imdur', 'nome de remedio'),
  (default, 'j', 'Janumet', 'nome de remedio'),
  (default, 'k', 'Klonopin', 'nome de remedio'),
  (default, 'l', 'Levitra', 'nome de remedio'),
  (default, 'm', 'Maxalt', 'nome de remedio'),
  (default, 'n', 'Neurontin', 'nome de remedio'),
  (default, 'o', 'Opana', 'nome de remedio'),
  (default, 'p', 'Percocet', 'nome de remedio'),
  (default, 'q', 'Qvar', 'nome de remedio'),
  (default, 'r', 'Ritalin', 'nome de remedio'),
  (default, 's', 'Strattera', 'nome de remedio'),
  (default, 't', 'Tylenol', 'nome de remedio'),
  (default, 'u', 'Uroxatral', 'nome de remedio'),
  (default, 'v', 'Valium', 'nome de remedio'),
  (default, 'w', 'Wellbutrin', 'nome de remedio'),
  (default, 'x', 'Xolair', 'nome de remedio'),
  (default, 'y', 'Yasmin', 'nome de remedio'),
  (default, 'z', 'Zocor', 'nome de remedio');

INSERT INTO public.themes_suggestions (id, first_letter, suggestion, theme)
VALUES
  (default, 'a', 'Ambien', 'nome de remedio'),
  (default, 'b', 'Boniva', 'nome de remedio'),
  (default, 'c', 'Cipro', 'nome de remedio'),
  (default, 'd', 'Depakote', 'nome de remedio'),
  (default, 'e', 'Effexor', 'nome de remedio'),
  (default, 'f', 'Fosamax', 'nome de remedio'),
  (default, 'g', 'Gardasil', 'nome de remedio'),
  (default, 'h', 'Haldol', 'nome de remedio'),
  (default, 'i', 'Inderal', 'nome de remedio'),
  (default, 'j', 'Januvia', 'nome de remedio'),
  (default, 'k', 'Keflex', 'nome de remedio'),
  (default, 'l', 'Lipitor', 'nome de remedio'),
  (default, 'm', 'Metadate', 'nome de remedio'),
  (default, 'n', 'Nardil', 'nome de remedio'),
  (default, 'o', 'Ortho Tri-Cyclen', 'nome de remedio'),
  (default, 'p', 'Paxil', 'nome de remedio'),
  (default, 'q', 'Quetiapine', 'nome de remedio'),
  (default, 'r', 'Risperdal', 'nome de remedio'),
  (default, 's', 'Serzone', 'nome de remedio'),
  (default, 't', 'Tegretol', 'nome de remedio'),
  (default, 'u', 'Uroxatral', 'nome de remedio'),
  (default, 'v', 'Vyvanse', 'nome de remedio'),
  (default, 'w', 'Wellbutrin', 'nome de remedio'),
  (default, 'x', 'Xanax', 'nome de remedio'),
  (default, 'y', 'Yaz', 'nome de remedio'),
  (default, 'z', 'Zoloft', 'nome de remedio');

INSERT INTO public.themes_suggestions (id, first_letter, suggestion, theme)
VALUES
  (default, 'a', 'Amarelo', 'cor'),
  (default, 'b', 'Branco', 'cor'),
  (default, 'c', 'Ciano', 'cor'),
  (default, 'd', 'Dourado', 'cor'),
  (default, 'e', 'Esmeralda', 'cor'),
  (default, 'f', 'Fúcsia', 'cor'),
  (default, 'g', 'Gris', 'cor'),
  (default, 'h', 'Hortela', 'cor'),
  (default, 'i', 'Índigo', 'cor'),
  (default, 'j', 'Jade', 'cor'),
  (default, 'k', 'Khaki', 'cor'),
  (default, 'l', 'Lavanda', 'cor'),
  (default, 'm', 'Marrom', 'cor'),
  (default, 'n', 'Nude', 'cor'),
  (default, 'o', 'Oliva', 'cor'),
  (default, 'p', 'Pêssego', 'cor'),
  (default, 'q', 'Quartz', 'cor'),
  (default, 'r', 'Rosa', 'cor'),
  (default, 's', 'Salmao', 'cor'),
  (default, 't', 'Turquesa', 'cor'),
  (default, 'u', 'Uva', 'cor'),
  (default, 'v', 'Vermelho', 'cor'),
  (default, 'w', 'Branco', 'cor'),
  (default, 'x', 'Xanadu', 'cor'),
  (default, 'y', 'Amarelo', 'cor'),
  (default, 'z', 'Zafiro', 'cor');

INSERT INTO public.themes_suggestions (id, first_letter, suggestion, theme)
VALUES
  (default, 'a', 'Açafrao', 'cor'),
  (default, 'b', 'Bronze', 'cor'),
  (default, 'c', 'Cereja', 'cor'),
  (default, 'd', 'Damasco', 'cor'),
  (default, 'e', 'Esmeralda', 'cor'),
  (default, 'f', 'Ferrugem', 'cor'),
  (default, 'g', 'Gengibre', 'cor'),
  (default, 'h', 'Hortela', 'cor'),
  (default, 'i', 'Índigo', 'cor'),
  (default, 'j', 'Jade', 'cor'),
  (default, 'k', 'Khaki', 'cor'),
  (default, 'l', 'Lilás', 'cor'),
  (default, 'm', 'Marfim', 'cor'),
  (default, 'n', 'Nude', 'cor'),
  (default, 'o', 'Orquidea', 'cor'),
  (default, 'p', 'Pêssego', 'cor'),
  (default, 'q', 'Quartz', 'cor'),
  (default, 'r', 'Rubi', 'cor'),
  (default, 's', 'Salmao', 'cor'),
  (default, 't', 'Turquesa', 'cor'),
  (default, 'u', 'Ultramarino', 'cor'),
  (default, 'v', 'Violeta', 'cor'),
  (default, 'w', 'Água-marinha', 'cor'),
  (default, 'x', 'Xanadu', 'cor'),
  (default, 'y', 'Amarelo', 'cor'),
  (default, 'z', 'Zinco', 'cor');

INSERT INTO public.themes_suggestions (id, first_letter, suggestion, theme)
VALUES
  (default, 'a', 'Azul-turquesa', 'cor'),
  (default, 'b', 'Bordô', 'cor'),
  (default, 'c', 'Creme', 'cor'),
  (default, 'd', 'Dourado', 'cor'),
  (default, 'e', 'Escarlate', 'cor'),
  (default, 'f', 'Fúcsia', 'cor'),
  (default, 'g', 'Grisalho', 'cor'),
  (default, 'h', 'Hortela', 'cor'),
  (default, 'i', 'Índigo', 'cor'),
  (default, 'j', 'Jade', 'cor'),
  (default, 'k', 'Kaki', 'cor'),
  (default, 'l', 'Lavanda', 'cor'),
  (default, 'm', 'Marrom-escuro', 'cor'),
  (default, 'n', 'Nude', 'cor'),
  (default, 'o', 'Orquidea', 'cor'),
  (default, 'p', 'Pêssego', 'cor'),
  (default, 'q', 'Quartz', 'cor'),
  (default, 'r', 'Rosa-choque', 'cor'),
  (default, 's', 'Salmao', 'cor'),
  (default, 't', 'Turquesa', 'cor'),
  (default, 'u', 'Uva', 'cor'),
  (default, 'v', 'Verde-limao', 'cor'),
  (default, 'w', 'Branco-gelo', 'cor'),
  (default, 'x', 'Xanadu', 'cor'),
  (default, 'y', 'Amarelo-ouro', 'cor'),
  (default, 'z', 'Zinco', 'cor');


INSERT INTO public.themes_suggestions (id, first_letter, suggestion, theme)
VALUES
  (default, 'a', 'Antilope', 'animal'),
  (default, 'b', 'Baleia', 'animal'),
  (default, 'c', 'Cachorro', 'animal'),
  (default, 'd', 'Delfim', 'animal'),
  (default, 'e', 'Elefante', 'animal'),
  (default, 'f', 'Flamingo', 'animal'),
  (default, 'g', 'Girafa', 'animal'),
  (default, 'h', 'Hipopótamo', 'animal'),
  (default, 'i', 'Iguana', 'animal'),
  (default, 'j', 'Jaguar', 'animal'),
  (default, 'k', 'Kanguru', 'animal'),
  (default, 'l', 'Leao', 'animal'),
  (default, 'm', 'Macaco', 'animal'),
  (default, 'n', 'Naja', 'animal'),
  (default, 'o', 'Orangotango', 'animal'),
  (default, 'p', 'Panda', 'animal'),
  (default, 'q', 'Quokka', 'animal'),
  (default, 'r', 'Raposa', 'animal'),
  (default, 's', 'Serpente', 'animal'),
  (default, 't', 'Tigre', 'animal'),
  (default, 'u', 'Urso', 'animal'),
  (default, 'v', 'Vaca', 'animal'),
  (default, 'w', 'Wombat', 'animal'),
  (default, 'x', 'Xareu', 'animal'),
  (default, 'y', 'Yak', 'animal'),
  (default, 'z', 'Zebra', 'animal');

INSERT INTO public.themes_suggestions (id, first_letter, suggestion, theme)
VALUES
  (default, 'a', 'Alce', 'animal'),
  (default, 'b', 'Búfalo', 'animal'),
  (default, 'c', 'Camaleao', 'animal'),
  (default, 'd', 'Doninha', 'animal'),
  (default, 'e', 'Esquilo', 'animal'),
  (default, 'f', 'Furao', 'animal'),
  (default, 'g', 'Gorila', 'animal'),
  (default, 'h', 'Hiena', 'animal'),
  (default, 'i', 'Ibis', 'animal'),
  (default, 'j', 'Jacare', 'animal'),
  (default, 'k', 'Kiwi', 'animal'),
  (default, 'l', 'Lince', 'animal'),
  (default, 'm', 'Morsa', 'animal'),
  (default, 'n', 'Narval', 'animal'),
  (default, 'o', 'Ouriço', 'animal'),
  (default, 'p', 'Pinguim', 'animal'),
  (default, 'q', 'Quero-quero', 'animal'),
  (default, 'r', 'Rena', 'animal'),
  (default, 's', 'Suricata', 'animal'),
  (default, 't', 'Tatu', 'animal'),
  (default, 'u', 'Urutu', 'animal'),
  (default, 'v', 'Vespa', 'animal'),
  (default, 'w', 'Wallaby', 'animal'),
  (default, 'x', 'Xiphias', 'animal'),
  (default, 'y', 'Yak', 'animal'),
  (default, 'z', 'Zibelina', 'animal');

INSERT INTO public.themes_suggestions (id, first_letter, suggestion, theme)
VALUES
  (default, 'a', 'Albatroz', 'animal'),
  (default, 'b', 'Babuino', 'animal'),
  (default, 'c', 'Caracol', 'animal'),
  (default, 'd', 'Dromedário', 'animal'),
  (default, 'e', 'Esquilo-voador', 'animal'),
  (default, 'f', 'Fuinha', 'animal'),
  (default, 'g', 'Guepardo', 'animal'),
  (default, 'h', 'Hipopótamo-pigmeu', 'animal'),
  (default, 'i', 'Iaque', 'animal'),
  (default, 'j', 'Jabuti', 'animal'),
  (default, 'k', 'Kakapo', 'animal'),
  (default, 'l', 'Lagarto', 'animal'),
  (default, 'm', 'Morsa-do-pacifico', 'animal'),
  (default, 'n', 'Nandu', 'animal'),
  (default, 'o', 'Orca', 'animal'),
  (default, 'p', 'Panda-vermelho', 'animal'),
  (default, 'q', 'Quati', 'animal'),
  (default, 'r', 'Rinoceronte-negro', 'animal'),
  (default, 's', 'Sapo', 'animal'),
  (default, 't', 'Tigre-de-bengala', 'animal'),
  (default, 'u', 'Urso-negro', 'animal'),
  (default, 'v', 'Vespa-asiática', 'animal'),
  (default, 'w', 'Wallaroo', 'animal'),
  (default, 'x', 'Xiphias', 'animal'),
  (default, 'y', 'Yeti', 'animal'),
  (default, 'z', 'Zibelina', 'animal');

INSERT INTO public.themes_suggestions (id, first_letter, suggestion, theme)
VALUES
  (default, 'a', 'Abacaxi', 'comida'),
  (default, 'b', 'Brócolis', 'comida'),
  (default, 'c', 'Camarao', 'comida'),
  (default, 'd', 'Damasco', 'comida'),
  (default, 'e', 'Espaguete', 'comida'),
  (default, 'f', 'Frango', 'comida'),
  (default, 'g', 'Gelato', 'comida'),
  (default, 'h', 'Hambúrguer', 'comida'),
  (default, 'i', 'Iogurte', 'comida'),
  (default, 'j', 'Jambalaya', 'comida'),
  (default, 'k', 'Kiwi', 'comida'),
  (default, 'l', 'Lasanha', 'comida'),
  (default, 'm', 'Molho de tomate', 'comida'),
  (default, 'n', 'Nhoque', 'comida'),
  (default, 'o', 'Omelete', 'comida'),
  (default, 'p', 'Pizza', 'comida'),
  (default, 'q', 'Queijo', 'comida'),
  (default, 'r', 'Risoto', 'comida'),
  (default, 's', 'Sushi', 'comida'),
  (default, 't', 'Taco', 'comida'),
  (default, 'u', 'Uvas', 'comida'),
  (default, 'v', 'Vatapá', 'comida'),
  (default, 'w', 'Waffle', 'comida'),
  (default, 'x', 'Xarope de bordo', 'comida'),
  (default, 'y', 'Yakitori', 'comida'),
  (default, 'z', 'Ziti', 'comida');

INSERT INTO public.themes_suggestions (id, first_letter, suggestion, theme)
VALUES
  (default, 'a', 'Arroz', 'comida'),
  (default, 'b', 'Batata', 'comida'),
  (default, 'c', 'Chocolate', 'comida'),
  (default, 'd', 'Doce de leite', 'comida'),
  (default, 'e', 'Empanada', 'comida'),
  (default, 'f', 'Feijoada', 'comida'),
  (default, 'g', 'Gnocchi', 'comida'),
  (default, 'h', 'Hummus', 'comida'),
  (default, 'i', 'Isca de peixe', 'comida'),
  (default, 'j', 'Jujuba', 'comida'),
  (default, 'k', 'Ketchup', 'comida'),
  (default, 'l', 'Linguine', 'comida'),
  (default, 'm', 'Mousse', 'comida'),
  (default, 'n', 'Nachos', 'comida'),
  (default, 'o', 'Ostra', 'comida'),
  (default, 'p', 'Pudim', 'comida'),
  (default, 'q', 'Quindim', 'comida'),
  (default, 'r', 'Ratatouille', 'comida'),
  (default, 's', 'Sanduiche', 'comida'),
  (default, 't', 'Tapioca', 'comida'),
  (default, 'u', 'Udon', 'comida'),
  (default, 'v', 'Vatapá', 'comida'),
  (default, 'w', 'Wrap', 'comida'),
  (default, 'x', 'Xarope de bordo', 'comida'),
  (default, 'y', 'Yakisoba', 'comida'),
  (default, 'z', 'Zabaione', 'comida');

INSERT INTO public.themes_suggestions (id, first_letter, suggestion, theme)
VALUES
  (default, 'a', 'Abobrinha', 'comida'),
  (default, 'b', 'Banana', 'comida'),
  (default, 'c', 'Cenoura', 'comida'),
  (default, 'd', 'Dorayaki', 'comida'),
  (default, 'e', 'Ervilha', 'comida'),
  (default, 'f', 'Fraldinha', 'comida'),
  (default, 'g', 'Gelatina', 'comida'),
  (default, 'h', 'Hambúrguer', 'comida'),
  (default, 'i', 'Injera', 'comida'),
  (default, 'j', 'Jiló', 'comida'),
  (default, 'k', 'Kebab', 'comida'),
  (default, 'l', 'Lula', 'comida'),
  (default, 'm', 'Molho barbecue', 'comida'),
  (default, 'n', 'Nectarina', 'comida'),
  (default, 'o', 'Omelete', 'comida'),
  (default, 'p', 'Paella', 'comida'),
  (default, 'q', 'Quiche', 'comida'),
  (default, 'r', 'Risoto de cogumelos', 'comida'),
  (default, 's', 'Sopa de lentilhas', 'comida'),
  (default, 't', 'Taco de peixe', 'comida'),
  (default, 'u', 'Udon', 'comida'),
  (default, 'v', 'Vatapá', 'comida'),
  (default, 'w', 'Waffle', 'comida'),
  (default, 'x', 'Xinxim', 'comida'),
  (default, 'y', 'Yakitori', 'comida'),
  (default, 'z', 'Ziti', 'comida');

INSERT INTO public.themes_suggestions (id, first_letter, suggestion, theme)
VALUES
  (default, 'a', 'Arquiteto', 'profissao'),
  (default, 'b', 'Bombeiro', 'profissao'),
  (default, 'c', 'Cirurgiao', 'profissao'),
  (default, 'd', 'Dentista', 'profissao'),
  (default, 'e', 'Engenheiro', 'profissao'),
  (default, 'f', 'Farmacêutico', 'profissao'),
  (default, 'g', 'Garçom', 'profissao'),
  (default, 'h', 'Historiador', 'profissao'),
  (default, 'i', 'Influenciador', 'profissao'),
  (default, 'j', 'Jornalista', 'profissao'),
  (default, 'k', 'Kinesiologista', 'profissao'),
  (default, 'l', 'Leiloeiro', 'profissao'),
  (default, 'm', 'Medico', 'profissao'),
  (default, 'n', 'Nutricionista', 'profissao'),
  (default, 'o', 'Ortopedista', 'profissao'),
  (default, 'p', 'Psicólogo', 'profissao'),
  (default, 'q', 'Quiropraxista', 'profissao'),
  (default, 'r', 'Radiologista', 'profissao'),
  (default, 's', 'Sociólogo', 'profissao'),
  (default, 't', 'Terapeuta', 'profissao'),
  (default, 'u', 'Urologista', 'profissao'),
  (default, 'v', 'Veterinário', 'profissao'),
  (default, 'w', 'Web designer', 'profissao'),
  (default, 'x', 'Xerife', 'profissao'),
  (default, 'y', 'Youtuber', 'profissao'),
  (default, 'z', 'Zootecnista', 'profissao');

INSERT INTO public.themes_suggestions (id, first_letter, suggestion, theme)
VALUES
  (default, 'a', 'Astronauta', 'profissao'),
  (default, 'b', 'Bibliotecário', 'profissao'),
  (default, 'c', 'Carteiro', 'profissao'),
  (default, 'd', 'Dermatologista', 'profissao'),
  (default, 'e', 'Economista', 'profissao'),
  (default, 'f', 'Fotógrafo', 'profissao'),
  (default, 'g', 'Geólogo', 'profissao'),
  (default, 'h', 'Hidrologista', 'profissao'),
  (default, 'i', 'Instrutor de ioga', 'profissao'),
  (default, 'j', 'Joalheiro', 'profissao'),
  (default, 'k', 'Kinesioterapeuta', 'profissao'),
  (default, 'l', 'Linguista', 'profissao'),
  (default, 'm', 'Matemático', 'profissao'),
  (default, 'n', 'Nanotecnólogo', 'profissao'),
  (default, 'o', 'Optometrista', 'profissao'),
  (default, 'p', 'Piloto', 'profissao'),
  (default, 'q', 'Quiromante', 'profissao'),
  (default, 'r', 'Repórter', 'profissao'),
  (default, 's', 'Sommelier', 'profissao'),
  (default, 't', 'Tradutor', 'profissao'),
  (default, 'u', 'Ufólogo', 'profissao'),
  (default, 'v', 'Vidraceiro', 'profissao'),
  (default, 'w', 'Web designer', 'profissao'),
  (default, 'x', 'Xerife', 'profissao'),
  (default, 'y', 'Youtuber', 'profissao'),
  (default, 'z', 'Zelador', 'profissao');

INSERT INTO public.themes_suggestions (id, first_letter, suggestion, theme)
VALUES
  (default, 'a', 'Acupunturista', 'profissao'),
  (default, 'b', 'Biólogo', 'profissao'),
  (default, 'c', 'Comissário de bordo', 'profissao'),
  (default, 'd', 'Dramaturgo', 'profissao'),
  (default, 'e', 'Eletricista', 'profissao'),
  (default, 'f', 'Fisioterapeuta', 'profissao'),
  (default, 'g', 'Geneticista', 'profissao'),
  (default, 'h', 'Hidroterapeuta', 'profissao'),
  (default, 'i', 'Ilustrador', 'profissao'),
  (default, 'j', 'Joalheiro', 'profissao'),
  (default, 'k', 'Kinesioterapeuta', 'profissao'),
  (default, 'l', 'Linguista', 'profissao'),
  (default, 'm', 'Meteorologista', 'profissao'),
  (default, 'n', 'Neurologista', 'profissao'),
  (default, 'o', 'Operador de guindaste', 'profissao'),
  (default, 'p', 'Psicanalista', 'profissao'),
  (default, 'q', 'Quiromante', 'profissao'),
  (default, 'r', 'Radiologista', 'profissao'),
  (default, 's', 'Sociólogo', 'profissao'),
  (default, 't', 'Terapeuta ocupacional', 'profissao'),
  (default, 'u', 'Urologista', 'profissao'),
  (default, 'v', 'Vendedor', 'profissao'),
  (default, 'w', 'Web designer', 'profissao'),
  (default, 'x', 'Xerife', 'profissao'),
  (default, 'y', 'Youtuber', 'profissao'),
  (default, 'z', 'Zelador', 'profissao');

INSERT INTO public.themes_suggestions (id, first_letter, suggestion, theme)
VALUES
  (default, 'a', 'Antebraço', 'partes corpo humano'),
  (default, 'b', 'Barriga', 'partes corpo humano'),
  (default, 'c', 'Cabeça', 'partes corpo humano'),
  (default, 'd', 'Dedo', 'partes corpo humano'),
  (default, 'e', 'Estômago', 'partes corpo humano'),
  (default, 'f', 'Face', 'partes corpo humano'),
  (default, 'g', 'Garganta', 'partes corpo humano'),
  (default, 'h', 'Hálux', 'partes corpo humano'),
  (default, 'i', 'Íris', 'partes corpo humano'),
  (default, 'j', 'Joelho', 'partes corpo humano'),
  (default, 'k', 'Kanekalon', 'partes corpo humano'),
  (default, 'l', 'Lombar', 'partes corpo humano'),
  (default, 'm', 'Mao', 'partes corpo humano'),
  (default, 'n', 'Nariz', 'partes corpo humano'),
  (default, 'o', 'Ombro', 'partes corpo humano'),
  (default, 'p', 'Perna', 'partes corpo humano'),
  (default, 'q', 'Queixo', 'partes corpo humano'),
  (default, 'r', 'Rosto', 'partes corpo humano'),
  (default, 's', 'Seio', 'partes corpo humano'),
  (default, 't', 'Tornozelo', 'partes corpo humano'),
  (default, 'u', 'Umbigo', 'partes corpo humano'),
  (default, 'v', 'Virilha', 'partes corpo humano'),
  (default, 'w', 'Wang', 'partes corpo humano'),
  (default, 'x', 'Xifoide', 'partes corpo humano'),
  (default, 'y', 'Yoni', 'partes corpo humano'),
  (default, 'z', 'Zona pelúcida', 'partes corpo humano');

INSERT INTO public.themes_suggestions (id, first_letter, suggestion, theme)
VALUES
  (default, 'a', 'Axila', 'partes corpo humano'),
  (default, 'b', 'Boca', 'partes corpo humano'),
  (default, 'c', 'Cilio', 'partes corpo humano'),
  (default, 'd', 'Dente', 'partes corpo humano'),
  (default, 'e', 'Esôfago', 'partes corpo humano'),
  (default, 'f', 'Figado', 'partes corpo humano'),
  (default, 'g', 'Gengiva', 'partes corpo humano'),
  (default, 'h', 'Hepatopâncreas', 'partes corpo humano'),
  (default, 'i', 'Íleo', 'partes corpo humano'),
  (default, 'j', 'Joanete', 'partes corpo humano'),
  (default, 'k', 'Kneecap', 'partes corpo humano'),
  (default, 'l', 'Laringe', 'partes corpo humano'),
  (default, 'm', 'Músculo', 'partes corpo humano'),
  (default, 'n', 'Nádega', 'partes corpo humano'),
  (default, 'o', 'Olho', 'partes corpo humano'),
  (default, 'p', 'Pe', 'partes corpo humano'),
  (default, 'q', 'Quadril', 'partes corpo humano'),
  (default, 'r', 'Rim', 'partes corpo humano'),
  (default, 's', 'Sangue', 'partes corpo humano'),
  (default, 't', 'Timpano', 'partes corpo humano'),
  (default, 'u', 'Úvula', 'partes corpo humano'),
  (default, 'v', 'Veia', 'partes corpo humano'),
  (default, 'w', 'Wrist', 'partes corpo humano'),
  (default, 'x', 'Xiphoid', 'partes corpo humano'),
  (default, 'y', 'Yolk sac', 'partes corpo humano'),
  (default, 'z', 'Zigoma', 'partes corpo humano');

INSERT INTO public.themes_suggestions (id, first_letter, suggestion, theme)
VALUES
  (default, 'a', 'Aorta', 'partes corpo humano'),
  (default, 'b', 'Brônquio', 'partes corpo humano'),
  (default, 'c', 'Cóccix', 'partes corpo humano'),
  (default, 'd', 'Diafragma', 'partes corpo humano'),
  (default, 'e', 'Esfincter', 'partes corpo humano'),
  (default, 'f', 'Fêmur', 'partes corpo humano'),
  (default, 'g', 'Glotis', 'partes corpo humano'),
  (default, 'h', 'Hormônio', 'partes corpo humano'),
  (default, 'i', 'Intestino', 'partes corpo humano'),
  (default, 'j', 'Junçao', 'partes corpo humano'),
  (default, 'k', 'Keratina', 'partes corpo humano'),
  (default, 'l', 'Laringe', 'partes corpo humano'),
  (default, 'm', 'Metacarpo', 'partes corpo humano'),
  (default, 'n', 'Nervo', 'partes corpo humano'),
  (default, 'o', 'Ovário', 'partes corpo humano'),
  (default, 'p', 'Pâncreas', 'partes corpo humano'),
  (default, 'q', 'Quadril', 'partes corpo humano'),
  (default, 'r', 'Rins', 'partes corpo humano'),
  (default, 's', 'Sinusite', 'partes corpo humano'),
  (default, 't', 'Traqueia', 'partes corpo humano'),
  (default, 'u', 'Uretra', 'partes corpo humano'),
  (default, 'v', 'Vertebra', 'partes corpo humano'),
  (default, 'w', 'Wrist', 'partes corpo humano'),
  (default, 'x', 'Xilofone', 'partes corpo humano'),
  (default, 'y', 'Yogurte', 'partes corpo humano'),
  (default, 'z', 'Ziper', 'partes corpo humano');

INSERT INTO public.themes_suggestions (id, first_letter, suggestion, theme)
VALUES
  (default, 'a', 'Angelina Jolie', 'celebridade'),
  (default, 'b', 'Brad Pitt', 'celebridade'),
  (default, 'c', 'Cristiano Ronaldo', 'celebridade'),
  (default, 'd', 'Dwayne Johnson', 'celebridade'),
  (default, 'e', 'Emma Watson', 'celebridade'),
  (default, 'f', 'Frida Kahlo', 'celebridade'),
  (default, 'g', 'George Clooney', 'celebridade'),
  (default, 'h', 'Hugh Jackman', 'celebridade'),
  (default, 'i', 'Idris Elba', 'celebridade'),
  (default, 'j', 'Jennifer Aniston', 'celebridade'),
  (default, 'k', 'Keanu Reeves', 'celebridade'),
  (default, 'l', 'Leonardo DiCaprio', 'celebridade'),
  (default, 'm', 'Meryl Streep', 'celebridade'),
  (default, 'n', 'Natalie Portman', 'celebridade'),
  (default, 'o', 'Oprah Winfrey', 'celebridade'),
  (default, 'p', 'Prince', 'celebridade'),
  (default, 'q', 'Queen Latifah', 'celebridade'),
  (default, 'r', 'Robert Downey Jr.', 'celebridade'),
  (default, 's', 'Scarlett Johansson', 'celebridade'),
  (default, 't', 'Tom Hanks', 'celebridade'),
  (default, 'u', 'Usain Bolt', 'celebridade'),
  (default, 'v', 'Viola Davis', 'celebridade'),
  (default, 'w', 'Will Smith', 'celebridade'),
  (default, 'x', 'Xuxa', 'celebridade'),
  (default, 'y', 'Yao Ming', 'celebridade'),
  (default, 'z', 'Zac Efron', 'celebridade');

INSERT INTO public.themes_suggestions (id, first_letter, suggestion, theme)
VALUES
  (default, 'a', 'Adele', 'celebridade'),
  (default, 'b', 'Beyonce', 'celebridade'),
  (default, 'c', 'Chris Hemsworth', 'celebridade'),
  (default, 'd', 'Daniel Radcliffe', 'celebridade'),
  (default, 'e', 'Ellen DeGeneres', 'celebridade'),
  (default, 'f', 'Felicity Jones', 'celebridade'),
  (default, 'g', 'Gal Gadot', 'celebridade'),
  (default, 'h', 'Harrison Ford', 'celebridade'),
  (default, 'i', 'Idris Elba', 'celebridade'),
  (default, 'j', 'Jennifer Lawrence', 'celebridade'),
  (default, 'k', 'Katy Perry', 'celebridade'),
  (default, 'l', 'Liam Neeson', 'celebridade'),
  (default, 'm', 'Mila Kunis', 'celebridade'),
  (default, 'n', 'Natalie Portman', 'celebridade'),
  (default, 'o', 'Oprah Winfrey', 'celebridade'),
  (default, 'p', 'Prince Harry', 'celebridade'),
  (default, 'q', 'Queen Latifah', 'celebridade'),
  (default, 'r', 'Robert Pattinson', 'celebridade'),
  (default, 's', 'Selena Gomez', 'celebridade'),
  (default, 't', 'Taylor Swift', 'celebridade'),
  (default, 'u', 'Uma Thurman', 'celebridade'),
  (default, 'v', 'Vin Diesel', 'celebridade'),
  (default, 'w', 'Winona Ryder', 'celebridade'),
  (default, 'x', 'Xuxa', 'celebridade'),
  (default, 'y', 'Yao Ming', 'celebridade'),
  (default, 'z', 'Zendaya', 'celebridade');

INSERT INTO public.themes_suggestions (id, first_letter, suggestion, theme)
VALUES
  (default, 'a', 'Alicia Keys', 'celebridade'),
  (default, 'b', 'Ben Affleck', 'celebridade'),
  (default, 'c', 'Cate Blanchett', 'celebridade'),
  (default, 'd', 'David Beckham', 'celebridade'),
  (default, 'e', 'Eva Longoria', 'celebridade'),
  (default, 'f', 'Freddie Mercury', 'celebridade'),
  (default, 'g', 'Gwyneth Paltrow', 'celebridade'),
  (default, 'h', 'Halle Berry', 'celebridade'),
  (default, 'i', 'Idris Elba', 'celebridade'),
  (default, 'j', 'Johnny Depp', 'celebridade'),
  (default, 'k', 'Kate Winslet', 'celebridade'),
  (default, 'l', 'Leonardo DiCaprio', 'celebridade'),
  (default, 'm', 'Morgan Freeman', 'celebridade'),
  (default, 'n', 'Natalie Portman', 'celebridade'),
  (default, 'o', 'Oprah Winfrey', 'celebridade'),
  (default, 'p', 'Penelope Cruz', 'celebridade'),
  (default, 'q', 'Queen Latifah', 'celebridade'),
  (default, 'r', 'Ryan Reynolds', 'celebridade'),
  (default, 's', 'Sandra Bullock', 'celebridade'),
  (default, 't', 'Tom Cruise', 'celebridade'),
  (default, 'u', 'Usain Bolt', 'celebridade'),
  (default, 'v', 'Viola Davis', 'celebridade'),
  (default, 'w', 'Will Ferrell', 'celebridade'),
  (default, 'x', 'Xuxa', 'celebridade'),
  (default, 'y', 'Yao Ming', 'celebridade'),
  (default, 'z', 'Zac Efron', 'celebridade');

INSERT INTO public.themes_suggestions (id, first_letter, suggestion, theme)
VALUES
  (default, 'a', 'Arsenal', 'times'),
  (default, 'b', 'Barcelona', 'times'),
  (default, 'c', 'Chelsea', 'times'),
  (default, 'd', 'Dallas Cowboys', 'times'),
  (default, 'e', 'Everton', 'times'),
  (default, 'f', 'FC Bayern Munich', 'times'),
  (default, 'g', 'Golden State Warriors', 'times'),
  (default, 'h', 'Houston Rockets', 'times'),
  (default, 'i', 'Inter de Milao', 'times'),
  (default, 'j', 'Juventus', 'times'),
  (default, 'k', 'Kansas City Chiefs', 'times'),
  (default, 'l', 'Liverpool', 'times'),
  (default, 'm', 'Manchester City', 'times'),
  (default, 'n', 'New England Patriots', 'times'),
  (default, 'o', 'Orlando Magic', 'times'),
  (default, 'p', 'Paris Saint-Germain', 'times'),
  (default, 'q', 'Queensland Reds', 'times'),
  (default, 'r', 'Real Madrid', 'times'),
  (default, 's', 'San Francisco 49ers', 'times'),
  (default, 't', 'Toronto Raptors', 'times'),
  (default, 'u', 'Utah Jazz', 'times'),
  (default, 'v', 'Vancouver Canucks', 'times'),
  (default, 'w', 'Washington Wizards', 'times'),
  (default, 'x', 'Xamax', 'times'),
  (default, 'y', 'Yankees', 'times'),
  (default, 'z', 'Zenit', 'times');

INSERT INTO public.themes_suggestions (id, first_letter, suggestion, theme)
VALUES
  (default, 'a', 'AC Milan', 'times'),
  (default, 'b', 'Boston Celtics', 'times'),
  (default, 'c', 'Chicago Bulls', 'times'),
  (default, 'd', 'Denver Broncos', 'times'),
  (default, 'e', 'Eagles (Philadelphia)', 'times'),
  (default, 'f', 'Flamengo', 'times'),
  (default, 'g', 'Green Bay Packers', 'times'),
  (default, 'h', 'Houston Astros', 'times'),
  (default, 'i', 'Indianapolis Colts', 'times'),
  (default, 'j', 'Jacksonville Jaguars', 'times'),
  (default, 'k', 'Kansas City Royals', 'times'),
  (default, 'l', 'Los Angeles Lakers', 'times'),
  (default, 'm', 'Miami Heat', 'times'),
  (default, 'n', 'New York Giants', 'times'),
  (default, 'o', 'Oakland Athletics', 'times'),
  (default, 'p', 'Pittsburgh Steelers', 'times'),
  (default, 'q', 'Queens Park Rangers', 'times'),
  (default, 'r', 'Rangers (New York)', 'times'),
  (default, 's', 'San Diego Padres', 'times'),
  (default, 't', 'Tampa Bay Buccaneers', 'times'),
  (default, 'u', 'Utah Jazz', 'times'),
  (default, 'v', 'Vancouver Whitecaps', 'times'),
  (default, 'w', 'Winnipeg Jets', 'times'),
  (default, 'x', 'Xamax', 'times'),
  (default, 'y', 'Yankees', 'times'),
  (default, 'z', 'Zenit', 'times');

INSERT INTO public.themes_suggestions (id, first_letter, suggestion, theme)
VALUES
  (default, 'a', 'Aston Villa', 'times'),
  (default, 'b', 'Baltimore Ravens', 'times'),
  (default, 'c', 'Celtic FC', 'times'),
  (default, 'd', 'Dallas Mavericks', 'times'),
  (default, 'e', 'Edmonton Oilers', 'times'),
  (default, 'f', 'FC Porto', 'times'),
  (default, 'g', 'Golden State Warriors', 'times'),
  (default, 'h', 'Houston Texans', 'times'),
  (default, 'i', 'Indianapolis Colts', 'times'),
  (default, 'j', 'Jacksonville Jaguars', 'times'),
  (default, 'k', 'Kansas City Chiefs', 'times'),
  (default, 'l', 'Los Angeles Lakers', 'times'),
  (default, 'm', 'Miami Dolphins', 'times'),
  (default, 'n', 'New England Patriots', 'times'),
  (default, 'o', 'Orlando Magic', 'times'),
  (default, 'p', 'Philadelphia Eagles', 'times'),
  (default, 'q', 'Queens Park Rangers', 'times'),
  (default, 'r', 'Real Madrid', 'times'),
  (default, 's', 'San Antonio Spurs', 'times'),
  (default, 't', 'Toronto Raptors', 'times'),
  (default, 'u', 'Utah Jazz', 'times'),
  (default, 'v', 'Vancouver Canucks', 'times'),
  (default, 'w', 'Washington Wizards', 'times'),
  (default, 'x', 'Xamax', 'times'),
  (default, 'y', 'Yankees', 'times'),
  (default, 'z', 'Zenit Saint Petersburg', 'times');

INSERT INTO public.themes_suggestions (id, first_letter, suggestion, theme)
VALUES
  (default, 'a', 'Aragorn', 'personagem ficticio'),
  (default, 'b', 'Batman', 'personagem ficticio'),
  (default, 'c', 'Captain America', 'personagem ficticio'),
  (default, 'd', 'Darth Vader', 'personagem ficticio'),
  (default, 'e', 'Elsa (Frozen)', 'personagem ficticio'),
  (default, 'f', 'Frodo Baggins', 'personagem ficticio'),
  (default, 'g', 'Gandalf', 'personagem ficticio'),
  (default, 'h', 'Harry Potter', 'personagem ficticio'),
  (default, 'i', 'Indiana Jones', 'personagem ficticio'),
  (default, 'j', 'James Bond', 'personagem ficticio'),
  (default, 'k', 'Katniss Everdeen', 'personagem ficticio'),
  (default, 'l', 'Lara Croft', 'personagem ficticio'),
  (default, 'm', 'Mickey Mouse', 'personagem ficticio'),
  (default, 'n', 'Neo (Matrix)', 'personagem ficticio'),
  (default, 'o', 'Obi-Wan Kenobi', 'personagem ficticio'),
  (default, 'p', 'Pikachu', 'personagem ficticio'),
  (default, 'q', 'Qui-Gon Jinn', 'personagem ficticio'),
  (default, 'r', 'Ron Weasley', 'personagem ficticio'),
  (default, 's', 'Superman', 'personagem ficticio'),
  (default, 't', 'Thor', 'personagem ficticio'),
  (default, 'u', 'Uma Thurman (Kill Bill)', 'personagem ficticio'),
  (default, 'v', 'Voldemort', 'personagem ficticio'),
  (default, 'w', 'Winnie the Pooh', 'personagem ficticio'),
  (default, 'x', 'Xena (Xena: A Princesa Guerreira)', 'personagem ficticio'),
  (default, 'y', 'Yoda', 'personagem ficticio'),
  (default, 'z', 'Zorro', 'personagem ficticio');

INSERT INTO public.themes_suggestions (id, first_letter, suggestion, theme)
VALUES
  (default, 'a', 'Aragorn', 'personagem ficticio'),
  (default, 'b', 'Bilbo Bolseiro', 'personagem ficticio'),
  (default, 'c', 'Cinderela', 'personagem ficticio'),
  (default, 'd', 'Dory (Procurando Nemo)', 'personagem ficticio'),
  (default, 'e', 'Elsa (Frozen)', 'personagem ficticio'),
  (default, 'f', 'Frodo Bolseiro', 'personagem ficticio'),
  (default, 'g', 'Gollum', 'personagem ficticio'),
  (default, 'h', 'Hercules', 'personagem ficticio'),
  (default, 'i', 'Iago (Aladdin)', 'personagem ficticio'),
  (default, 'j', 'Jack Sparrow', 'personagem ficticio'),
  (default, 'k', 'Kida Nedakh', 'personagem ficticio'),
  (default, 'l', 'Lilo (Lilo & Stitch)', 'personagem ficticio'),
  (default, 'm', 'Mulan', 'personagem ficticio'),
  (default, 'n', 'Nemo (Procurando Nemo)', 'personagem ficticio'),
  (default, 'o', 'Olaf (Frozen)', 'personagem ficticio'),
  (default, 'p', 'Peter Pan', 'personagem ficticio'),
  (default, 'q', 'Quasimodo', 'personagem ficticio'),
  (default, 'r', 'Rapunzel', 'personagem ficticio'),
  (default, 's', 'Simba', 'personagem ficticio'),
  (default, 't', 'Tiana (A Princesa e o Sapo)', 'personagem ficticio'),
  (default, 'u', 'Ursinho Pooh', 'personagem ficticio'),
  (default, 'v', 'Vanellope Von Schweetz', 'personagem ficticio'),
  (default, 'w', 'Wally (Wall-E)', 'personagem ficticio'),
  (default, 'x', 'Xerife Woody', 'personagem ficticio'),
  (default, 'y', 'Yzma', 'personagem ficticio'),
  (default, 'z', 'Zazu (O Rei Leao)', 'personagem ficticio');

INSERT INTO public.themes_suggestions (id, first_letter, suggestion, theme)
VALUES
  (default, 'a', 'Aragorn', 'personagem ficticio'),
  (default, 'b', 'Bart Simpson', 'personagem ficticio'),
  (default, 'c', 'Cruella de Vil', 'personagem ficticio'),
  (default, 'd', 'Donkey (Shrek)', 'personagem ficticio'),
  (default, 'e', 'Elsa (Frozen)', 'personagem ficticio'),
  (default, 'f', 'Fiona (Shrek)', 'personagem ficticio'),
  (default, 'g', 'Gandalf', 'personagem ficticio'),
  (default, 'h', 'Hannibal Lecter', 'personagem ficticio'),
  (default, 'i', 'Iron Man', 'personagem ficticio'),
  (default, 'j', 'Joker (Batman)', 'personagem ficticio'),
  (default, 'k', 'Kermit the Frog', 'personagem ficticio'),
  (default, 'l', 'Lara Croft', 'personagem ficticio'),
  (default, 'm', 'Mickey Mouse', 'personagem ficticio'),
  (default, 'n', 'Nemo (Procurando Nemo)', 'personagem ficticio'),
  (default, 'o', 'Obi-Wan Kenobi', 'personagem ficticio'),
  (default, 'p', 'Pikachu', 'personagem ficticio'),
  (default, 'q', 'Queen Ravenna (Branca de Neve e o Caçador)', 'personagem ficticio'),
  (default, 'r', 'Rapunzel', 'personagem ficticio'),
  (default, 's', 'Sherlock Holmes', 'personagem ficticio'),
  (default, 't', 'Thor', 'personagem ficticio'),
  (default, 'u', 'Ursula (A Pequena Sereia)', 'personagem ficticio'),
  (default, 'v', 'Voldemort', 'personagem ficticio'),
  (default, 'w', 'Wolverine', 'personagem ficticio'),
  (default, 'x', 'Xena (Xena: A Princesa Guerreira)', 'personagem ficticio'),
  (default, 'y', 'Yoda', 'personagem ficticio'),
  (default, 'z', 'Zorro', 'personagem ficticio');

INSERT INTO public.themes_suggestions (id, first_letter, suggestion, theme)
VALUES
  (default, 'a', 'Aladdin', 'personagem ficticio'),
  (default, 'b', 'Belle (A Bela e a Fera)', 'personagem ficticio'),
  (default, 'c', 'Chewbacca', 'personagem ficticio'),
  (default, 'd', 'Dory (Procurando Nemo)', 'personagem ficticio'),
  (default, 'e', 'Elsa (Frozen)', 'personagem ficticio'),
  (default, 'f', 'Frodo Bolseiro', 'personagem ficticio'),
  (default, 'g', 'Gandalf', 'personagem ficticio'),
  (default, 'h', 'Harry Potter', 'personagem ficticio'),
  (default, 'i', 'Indiana Jones', 'personagem ficticio'),
  (default, 'j', 'Jack Sparrow', 'personagem ficticio'),
  (default, 'k', 'Katniss Everdeen', 'personagem ficticio'),
  (default, 'l', 'Lara Croft', 'personagem ficticio'),
  (default, 'm', 'Mickey Mouse', 'personagem ficticio'),
  (default, 'n', 'Nemo (Procurando Nemo)', 'personagem ficticio'),
  (default, 'o', 'Olaf (Frozen)', 'personagem ficticio'),
  (default, 'p', 'Peter Pan', 'personagem ficticio'),
  (default, 'q', 'Quasimodo', 'personagem ficticio'),
  (default, 'r', 'Rapunzel', 'personagem ficticio'),
  (default, 's', 'Simba', 'personagem ficticio'),
  (default, 't', 'Tiana (A Princesa e o Sapo)', 'personagem ficticio'),
  (default, 'u', 'Ursinho Pooh', 'personagem ficticio'),
  (default, 'v', 'Vanellope Von Schweetz', 'personagem ficticio'),
  (default, 'w', 'Wally (Wall-E)', 'personagem ficticio'),
  (default, 'x', 'Xerife Woody', 'personagem ficticio'),
  (default, 'y', 'Yzma', 'personagem ficticio'),
  (default, 'z', 'Zazu (O Rei Leao)', 'personagem ficticio');

INSERT INTO public.themes_suggestions (id, first_letter, suggestion, theme)
VALUES
  (default, 'a', 'Amável', 'minha sogra e'),
  (default, 'b', 'Brilhante', 'minha sogra e'),
  (default, 'c', 'Carismática', 'minha sogra e'),
  (default, 'd', 'Divertida', 'minha sogra e'),
  (default, 'e', 'Encantadora', 'minha sogra e'),
  (default, 'f', 'Fascinante', 'minha sogra e'),
  (default, 'g', 'Generosa', 'minha sogra e'),
  (default, 'h', 'Honesta', 'minha sogra e'),
  (default, 'i', 'Incrivel', 'minha sogra e'),
  (default, 'j', 'Jovial', 'minha sogra e'),
  (default, 'k', 'Kaleidoscópica', 'minha sogra e'),
  (default, 'l', 'Leal', 'minha sogra e'),
  (default, 'm', 'Magnifica', 'minha sogra e'),
  (default, 'n', 'Notável', 'minha sogra e'),
  (default, 'o', 'Otimista', 'minha sogra e'),
  (default, 'p', 'Pacifica', 'minha sogra e'),
  (default, 'q', 'Querida', 'minha sogra e'),
  (default, 'r', 'Radiante', 'minha sogra e'),
  (default, 's', 'Sincera', 'minha sogra e'),
  (default, 't', 'Talentosa', 'minha sogra e'),
  (default, 'u', 'Única', 'minha sogra e'),
  (default, 'v', 'Vibrante', 'minha sogra e'),
  (default, 'w', 'Wagneriana', 'minha sogra e'),
  (default, 'x', 'Xenófoba', 'minha sogra e'),
  (default, 'y', 'Yogica', 'minha sogra e'),
  (default, 'z', 'Zelosa', 'minha sogra e');

INSERT INTO public.themes_suggestions (id, first_letter, suggestion, theme)
VALUES
  (default, 'a', 'Atenciosa', 'minha sogra e'),
  (default, 'b', 'Bem-humorada', 'minha sogra e'),
  (default, 'c', 'Carinhosa', 'minha sogra e'),
  (default, 'd', 'Dedicada', 'minha sogra e'),
  (default, 'e', 'Elegante', 'minha sogra e'),
  (default, 'f', 'Festeira', 'minha sogra e'),
  (default, 'g', 'Generosa', 'minha sogra e'),
  (default, 'h', 'Hospitaleira', 'minha sogra e'),
  (default, 'i', 'Inteligente', 'minha sogra e'),
  (default, 'j', 'Justa', 'minha sogra e'),
  (default, 'k', 'Kaleidoscópica', 'minha sogra e'),
  (default, 'l', 'Leal', 'minha sogra e'),
  (default, 'm', 'Maravilhosa', 'minha sogra e'),
  (default, 'n', 'Notável', 'minha sogra e'),
  (default, 'o', 'Otimista', 'minha sogra e'),
  (default, 'p', 'Paciente', 'minha sogra e'),
  (default, 'q', 'Querida', 'minha sogra e'),
  (default, 'r', 'Respeitosa', 'minha sogra e'),
  (default, 's', 'Sábia', 'minha sogra e'),
  (default, 't', 'Talentosa', 'minha sogra e'),
  (default, 'u', 'Única', 'minha sogra e'),
  (default, 'v', 'Valorosa', 'minha sogra e'),
  (default, 'w', 'Wagneriana', 'minha sogra e'),
  (default, 'x', 'Xenófoba', 'minha sogra e'),
  (default, 'y', 'Yogica', 'minha sogra e'),
  (default, 'z', 'Zelosa', 'minha sogra e');

INSERT INTO public.themes_suggestions (id, first_letter, suggestion, theme)
VALUES
  (default, 'a', 'Agradável', 'minha sogra e'),
  (default, 'b', 'Benevolente', 'minha sogra e'),
  (default, 'c', 'Compreensiva', 'minha sogra e'),
  (default, 'd', 'Dedicada', 'minha sogra e'),
  (default, 'e', 'Encantadora', 'minha sogra e'),
  (default, 'f', 'Festeira', 'minha sogra e'),
  (default, 'g', 'Generosa', 'minha sogra e'),
  (default, 'h', 'Hospitaleira', 'minha sogra e'),
  (default, 'i', 'Inteligente', 'minha sogra e'),
  (default, 'j', 'Justa', 'minha sogra e'),
  (default, 'k', 'Kaleidoscópica', 'minha sogra e'),
  (default, 'l', 'Leal', 'minha sogra e'),
  (default, 'm', 'Maravilhosa', 'minha sogra e'),
  (default, 'n', 'Notável', 'minha sogra e'),
  (default, 'o', 'Otimista', 'minha sogra e'),
  (default, 'p', 'Paciente', 'minha sogra e'),
  (default, 'q', 'Querida', 'minha sogra e'),
  (default, 'r', 'Respeitosa', 'minha sogra e'),
  (default, 's', 'Sábia', 'minha sogra e'),
  (default, 't', 'Talentosa', 'minha sogra e'),
  (default, 'u', 'Única', 'minha sogra e'),
  (default, 'v', 'Valorosa', 'minha sogra e'),
  (default, 'w', 'Wagneriana', 'minha sogra e'),
  (default, 'x', 'Xenófoba', 'minha sogra e'),
  (default, 'y', 'Yogica', 'minha sogra e'),
  (default, 'z', 'Zelosa', 'minha sogra e');

INSERT INTO public.themes_suggestions (id, first_letter, suggestion, theme)
VALUES
  (default, 'a', 'Abacaxi', 'fruta'),
  (default, 'b', 'Banana', 'fruta'),
  (default, 'c', 'Cereja', 'fruta'),
  (default, 'd', 'Damasco', 'fruta'),
  (default, 'e', 'Ervilha', 'fruta'),
  (default, 'f', 'Framboesa', 'fruta'),
  (default, 'g', 'Goiaba', 'fruta'),
  (default, 'h', 'Hortela', 'fruta'),
  (default, 'i', 'Iogurte', 'fruta'),
  (default, 'j', 'Jabuticaba', 'fruta'),
  (default, 'k', 'Kiwi', 'fruta'),
  (default, 'l', 'Limao', 'fruta'),
  (default, 'm', 'Maça', 'fruta'),
  (default, 'n', 'Nectarina', 'fruta'),
  (default, 'o', 'Laranja', 'fruta'),
  (default, 'p', 'Pêssego', 'fruta'),
  (default, 'q', 'Quiui', 'fruta'),
  (default, 'r', 'Roma', 'fruta'),
  (default, 's', 'Morango', 'fruta'),
  (default, 't', 'Tangerina', 'fruta'),
  (default, 'u', 'Uva', 'fruta'),
  (default, 'v', 'Vagem', 'fruta'),
  (default, 'w', 'Wassabi', 'fruta'),
  (default, 'x', 'Ximbu', 'fruta'),
  (default, 'y', 'Yuzu', 'fruta'),
  (default, 'z', 'Zimbro', 'fruta');


INSERT INTO public.themes_suggestions (id, first_letter, suggestion, theme)
VALUES
  (default, 'a', 'Ameixa', 'fruta'),
  (default, 'b', 'Bergamota', 'fruta'),
  (default, 'c', 'Caju', 'fruta'),
  (default, 'd', 'Drupe', 'fruta'),
  (default, 'e', 'Espinheiro', 'fruta'),
  (default, 'f', 'Figo', 'fruta'),
  (default, 'g', 'Groselha', 'fruta'),
  (default, 'h', 'Hidromelao', 'fruta'),
  (default, 'i', 'Ingá', 'fruta'),
  (default, 'j', 'Jenipapo', 'fruta'),
  (default, 'k', 'Kinkan', 'fruta'),
  (default, 'l', 'Lichia', 'fruta'),
  (default, 'm', 'Manga', 'fruta'),
  (default, 'n', 'Nêspera', 'fruta'),
  (default, 'o', 'Oliva', 'fruta'),
  (default, 'p', 'Pera', 'fruta'),
  (default, 'q', 'Quiui', 'fruta'),
  (default, 'r', 'Rambuta', 'fruta'),
  (default, 's', 'Sapota', 'fruta'),
  (default, 't', 'Tomate', 'fruta'),
  (default, 'u', 'Umbu', 'fruta'),
  (default, 'v', 'Vagem', 'fruta'),
  (default, 'w', 'Wampi', 'fruta'),
  (default, 'x', 'Xoconostle', 'fruta'),
  (default, 'y', 'Yamamomo', 'fruta'),
  (default, 'z', 'Zimbro', 'fruta');

INSERT INTO public.themes_suggestions (id, first_letter, suggestion, theme)
VALUES
  (default, 'a', 'Acerola', 'fruta'),
  (default, 'b', 'Biriba', 'fruta'),
  (default, 'c', 'Cajá', 'fruta'),
  (default, 'd', 'Damasco', 'fruta'),
  (default, 'e', 'Embaúba', 'fruta'),
  (default, 'f', 'Figo', 'fruta'),
  (default, 'g', 'Goiaba', 'fruta'),
  (default, 'h', 'Hawthorn', 'fruta'),
  (default, 'i', 'Imbu', 'fruta'),
  (default, 'j', 'Jamelao', 'fruta'),
  (default, 'k', 'Kiwi', 'fruta'),
  (default, 'l', 'Lichia', 'fruta'),
  (default, 'm', 'Mamao', 'fruta'),
  (default, 'n', 'Nectarina', 'fruta'),
  (default, 'o', 'Oliva', 'fruta'),
  (default, 'p', 'Pitanga', 'fruta'),
  (default, 'q', 'Quivi', 'fruta'),
  (default, 'r', 'Roma', 'fruta'),
  (default, 's', 'Seriguela', 'fruta'),
  (default, 't', 'Tangerina', 'fruta'),
  (default, 'u', 'Uva', 'fruta'),
  (default, 'v', 'Vagem', 'fruta'),
  (default, 'w', 'Wassabi', 'fruta'),
  (default, 'x', 'Ximbu', 'fruta'),
  (default, 'y', 'Yambo', 'fruta'),
  (default, 'z', 'Zalacca', 'fruta');

INSERT INTO public.themes_suggestions (id, first_letter, suggestion, theme)
VALUES
  (default, 'a', 'Apple', 'marca'),
  (default, 'b', 'Bose', 'marca'),
  (default, 'c', 'Coca-Cola', 'marca'),
  (default, 'd', 'Disney', 'marca'),
  (default, 'e', 'Elle', 'marca'),
  (default, 'f', 'Ford', 'marca'),
  (default, 'g', 'Google', 'marca'),
  (default, 'h', 'Honda', 'marca'),
  (default, 'i', 'IBM', 'marca'),
  (default, 'j', 'Jaguar', 'marca'),
  (default, 'k', 'Kodak', 'marca'),
  (default, 'l', 'Lexus', 'marca'),
  (default, 'm', 'McDonalds', 'marca'),
  (default, 'n', 'Nike', 'marca'),
  (default, 'o', 'Oracle', 'marca'),
  (default, 'p', 'Puma', 'marca'),
  (default, 'q', 'Qantas', 'marca'),
  (default, 'r', 'Reebok', 'marca'),
  (default, 's', 'Sony', 'marca'),
  (default, 't', 'Toyota', 'marca'),
  (default, 'u', 'Under Armour', 'marca'),
  (default, 'v', 'Volkswagen', 'marca'),
  (default, 'w', 'Walmart', 'marca'),
  (default, 'x', 'Xerox', 'marca'),
  (default, 'y', 'Yahoo', 'marca'),
  (default, 'z', 'Zara', 'marca');

INSERT INTO public.themes_suggestions (id, first_letter, suggestion, theme)
VALUES
  (default, 'a', 'Audi', 'marca'),
  (default, 'b', 'Burberry', 'marca'),
  (default, 'c', 'Chanel', 'marca'),
  (default, 'd', 'Dior', 'marca'),
  (default, 'e', 'Estee Lauder', 'marca'),
  (default, 'f', 'Ferrari', 'marca'),
  (default, 'g', 'Gucci', 'marca'),
  (default, 'h', 'Hermès', 'marca'),
  (default, 'i', 'Intel', 'marca'),
  (default, 'j', 'Jeep', 'marca'),
  (default, 'k', 'Kia', 'marca'),
  (default, 'l', 'Lacoste', 'marca'),
  (default, 'm', 'Maserati', 'marca'),
  (default, 'n', 'Nikon', 'marca'),
  (default, 'o', 'Oreo', 'marca'),
  (default, 'p', 'Porsche', 'marca'),
  (default, 'q', 'Quiksilver', 'marca'),
  (default, 'r', 'Ralph Lauren', 'marca'),
  (default, 's', 'Samsung', 'marca'),
  (default, 't', 'Tiffany & Co.', 'marca'),
  (default, 'u', 'Uniqlo', 'marca'),
  (default, 'v', 'Versace', 'marca'),
  (default, 'w', 'Wells Fargo', 'marca'),
  (default, 'x', 'Xiaomi', 'marca'),
  (default, 'y', 'Yves Saint Laurent', 'marca'),
  (default, 'z', 'Zegna', 'marca');

INSERT INTO public.themes_suggestions (id, first_letter, suggestion, theme)
VALUES
  (default, 'a', 'Acura', 'marca'),
  (default, 'b', 'Bose', 'marca'),
  (default, 'c', 'Cadillac', 'marca'),
  (default, 'd', 'Dell', 'marca'),
  (default, 'e', 'Esso', 'marca'),
  (default, 'f', 'Fujifilm', 'marca'),
  (default, 'g', 'Gap', 'marca'),
  (default, 'h', 'Heinz', 'marca'),
  (default, 'i', 'Ikea', 'marca'),
  (default, 'j', 'J.Crew', 'marca'),
  (default, 'k', 'Kelloggs', 'marca'),
  (default, 'l', 'Lego', 'marca'),
  (default, 'm', 'Mitsubishi', 'marca'),
  (default, 'n', 'Nestle', 'marca'),
  (default, 'o', 'Olay', 'marca'),
  (default, 'p', 'Panasonic', 'marca'),
  (default, 'q', 'Quaker Oats', 'marca'),
  (default, 'r', 'Ritz-Carlton', 'marca'),
  (default, 's', 'Subaru', 'marca'),
  (default, 't', 'Toshiba', 'marca'),
  (default, 'u', 'Umbro', 'marca'),
  (default, 'v', 'Vans', 'marca'),
  (default, 'w', 'Wrigley', 'marca'),
  (default, 'x', 'Xbox', 'marca'),
  (default, 'y', 'Yamaha', 'marca'),
  (default, 'z', 'Zara', 'marca');

